# anchor

_defaults:
  docker: &docker
    conditions:
      - "[STATUS] == 200"
      - "[BODY].State.Status == running"
    ui:
      hide-hostname: true

# config

alerting:
  discord:
    default-alert:
      failure-threshold: 5
      success-threshold: 3
      send-on-resolved: true

storage:
  type: postgres
  path: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable"

ui:
  title: "Gatus for penguins - pocha.moe"
  header: "Uptime for penguins"
  description: "Gatus monitoring for pocha.moe."
  logo: "https://pocha.moe/pipfavicon.png"

endpoints:
  - name: bot
    group: mafuyu
    <<: *docker
    url: "${SOCKET_PROXY}/containers/mafuyu-bot-1/json"
    alerts:
      - type: discord
  
  # - name: musicpresence
  #   group: pocha.moe 
  #   <<: *docker
  #   url: "${SOCKET_PROXY}/containers/media-players-site-1/json"
  #   alerts:
  #     - type: discord

  - name: api
    group: pocha.moe
    url: "https://api.pocha.moe/v1/health"
    conditions:
      - "[STATUS] == 200"
      - "[BODY].status == ok"
  
  - name: homepage
    group: pocha.moe
    url: "https://pocha.moe"
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: discord