# config

alerting:
  discord:
    default-alert:
      failure-threshold: 5
      success-threshold: 3
      send-on-resolved: true

storage:
  type: postgres
  path: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable"

ui:
  title: "Gatus for penguins - pocha.moe"
  header: "Uptime for penguins"
  login-subtitle: "and also for non-penguins"
  description: "Gatus monitoring for pocha.moe."
  dashboard-heading: "Uptime check!"
  dashboard-subheading: "Uptime for my one bot and 3 subdomains."
  logo: "https://pocha.moe/pipfavicon.png"
  buttons:
    - name: Source
      link: https://github.com/mercurialworld/dreamcatching

endpoints:
  - name: bot
    group: mafuyu
    url: "mercurial:7001/health"
    conditions:
      - "[STATUS] == 200"
      - "[BODY].status == ok"
    ui:
      hide-hostname: true
    alerts:
      - type: discord
  
  - name: api
    group: pocha.moe
    url: "https://api.pocha.moe/v1/health"
    conditions:
      - "[STATUS] == 200"
      - "[BODY].status == ok"
    alerts:
      - type: discord
  
  - name: cache 
    group: pocha.moe
    url: "https://cache.pocha.moe/health"
    conditions:
      - "[STATUS] == 200"
      - "[BODY].status == ok"
    alerts:
      - type: discord

  - name: homepage
    group: pocha.moe
    url: "https://pocha.moe"
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: discord