version: 0.0
os: linux 
files:
  - source: /
    destination: /var/lib/codedeploy-apps/dreamcatching
file_exists_behavior: OVERWRITE
hooks:
  ApplicationStop:
    - location: hooks/ApplicationStop.sh
      timeout: 60
  ApplicationStart:
    - location: hooks/ApplicationStart.sh
      timeout: 120