# add stuff here
services:
  gatus:
    image: twinproduction/gatus:latest
    ports:
      - 5000:8080
    environment:
      SOCKET_PROXY: http://socket-proxy:2375/v1.45
    volumes:
      - ./gatus:/config
      - gatus_data:/data
    networks:
      - web
    restart: unless-stopped
    depends_on:
      - postgres
      - socket-proxy
  
  postgres:
    image: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: unless-stopped  
    environment:
      POSTGRES_DB: gatus
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    networks:
      - web
  
  socket-proxy:
    image: lscr.io/linuxserver/socket-proxy:latest
    container_name: socket-proxy
    environment:
      - CONTAINERS=1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    read_only: true
    tmpfs:
      - /run
    networks:
      - web

networks:
  web:

volumes:
  pg_data:
  gatus_data: