# add stuff here
services:
  gatus:
    image: twinproduction/gatus:latest
    ports:
      - 5201:8080
    environment:
      SOCKET_PROXY: http://socket-proxy:2375/v1.45
      POSTGRES_DB: gatus
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    volumes:
      - ./gatus:/config
      - gatus_data:/data
    secrets:
      - source: gatus-secrets
        target: /config/gatus-secrets.yml
    restart: unless-stopped
    depends_on:
      - postgres
      - socket-proxy
  
  postgres:
    image: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: unless-stopped  
    environment:
      POSTGRES_DB: gatus
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
  
  socket-proxy:
    image: lscr.io/linuxserver/socket-proxy:latest
    container_name: socket-proxy
    environment:
      - CONTAINERS=1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    read_only: true
    tmpfs:
      - /run

  docker-state-exporter:
    image: karugaru/docker_state_exporter
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    ports:
      - "127.0.0.1:5202:8080"
    restart: unless-stopped

secrets:
  gatus-secrets:
    file: gatus-secrets.yml

volumes:
  pg_data:
  gatus_data:
